iterates through data, makes predictions using the 3 model
NoahSchiro/cs448_midterm pull request #10
Opened 2023-10-02 18:45 UTC by Kofwana

This updated code will create a file named "NLP_Pioneers.test.txt" with two columns (token and predicted_tag). It iterates through the test data, makes predictions using the three models (Bayes, SVM, Logistic Regression), and writes the token and predicted tag to the output file. Let me know if anything stands out regarding what I've implemented so far.

2023-10-02 19:21 UTC, NoahSchiro requested changes

2023-10-02 19:21 UTC, NoahSchiro commented on main.py
> +    train_data, test_data = get_data()
This is broken now because get_data returns three objects. The train, the val, and the test. Since val isn't used anywhere in this file, this line needs to be changed to

train_data, _, test_data = get_data()

2023-10-02 19:21 UTC, NoahSchiro commented on main.py
> +    test_features, test_labels = utils.prepare_data(test_data)
If we want to have that validate now, then we need to include it here as well (but it doesn't look like we use it anywhere in the rest of the file

2023-10-02 19:21 UTC, NoahSchiro commented on main.py
> +        for (feature, label) in zip(test_features, test_labels):
there are no test labels we have to just guess the POS tag given their token.

2023-10-02 19:21 UTC, NoahSchiro commented on main.py
> -        if pred == label:
There is no label and therefore no way for us to measure / report accuracy here.

2023-10-03 13:00 UTC, NoahSchiro commented
Kofwana this looks great. One comment: the output is something along the lines of ['NNP'] or whatever the POS is. Could we change this to simply be NNP so that it looks similar to the training input data?

Secondly, I am not sure I was right about the comma delimited output.... If you look at the training data it appears to be space delimited. Could we switch to this instead? Sorry for the confusion

2023-10-03 13:00 UTC, NoahSchiro approved these changes

2023-10-03 13:32 UTC, Kofwana reviewed
The output is now in the space-delimited format similar to the training input data, and the predicted POS tags will be without square brackets to match the format.

2023-10-03 23:11 UTC, afq5024 approved these changes

2023-10-05 15:00 UTC, merged